<?xml version="1.0"?>
<package format="3">
  <name>triago_robot</name>
  <version>0.8.2</version>
  <description>The triago_robot package</description>

  <maintainer email="viviana.morlando@pal-robotics.com">Viviana Morlando</maintainer>

  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>triago_bringup</exec_depend>
  <exec_depend>triago_controller_configuration</exec_depend>
  <exec_depend>triago_description</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
