gravity_compensation_controller:
  ros__parameters:
    command_joints: ['arm_right_1_joint', 'arm_right_2_joint', 'arm_right_3_joint', 'arm_right_4_joint', 'arm_right_5_joint', 'arm_right_6_joint', 'arm_right_7_joint', 'arm_left_1_joint', 'arm_left_2_joint', 'arm_left_3_joint', 'arm_left_4_joint', 'arm_left_5_joint', 'arm_left_6_joint', 'arm_left_7_joint']

    root_link: "torso_lift_link"

    tip_links: ["arm_left_tool_link", "arm_right_tool_link"]

    torque_gain: 1.0

    parameters:
      arm_right_1_joint:
        motor_torque_constant: -0.05
        reduction_ratio: 101.0
      arm_right_2_joint:
        motor_torque_constant: -0.069
        reduction_ratio: 121.0
      arm_right_3_joint:
        motor_torque_constant: -0.035
        reduction_ratio: 101.0
      arm_right_4_joint:
        motor_torque_constant: 0.04
        reduction_ratio: 101.0
      arm_right_5_joint:
        motor_torque_constant: -0.17
        reduction_ratio: 101.0
      arm_right_6_joint:
        motor_torque_constant: -0.03
        reduction_ratio: 101.0
      arm_right_7_joint:
        motor_torque_constant: 0.103
        reduction_ratio: 101.0
      arm_left_1_joint:
        motor_torque_constant: -0.103
        reduction_ratio: 101.0
      arm_left_2_joint:
        motor_torque_constant: -0.061
        reduction_ratio: 121.0
      arm_left_3_joint:
        motor_torque_constant: -0.042
        reduction_ratio: 101.0
      arm_left_4_joint:
        motor_torque_constant: 0.032
        reduction_ratio: 101.0
      arm_left_5_joint:
        motor_torque_constant: -1.2
        reduction_ratio: 101.0
      arm_left_6_joint:
        motor_torque_constant: -0.038
        reduction_ratio: 101.0
      arm_left_7_joint:
        motor_torque_constant: 0.103
        reduction_ratio: 101.0
