/play_motion2:
  ros__parameters:
    motions:
      home:
        joints: [torso_lift_joint, arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint, arm_left_7_joint,
        arm_head_1_joint, arm_head_2_joint, arm_head_3_joint, arm_head_4_joint, arm_head_5_joint, arm_head_6_joint, arm_head_7_joint]
        times_from_start: [0.0, 5.0, 10.0]
        positions: [0.17202, 1.8557, -1.5919, 0.35538, -2.0502, 0.10524, -1.20, 0.0, -1.57, -1.6008, -0.34892, -1.9818, 0.10153, -1.20, 0.0,
                    0.1761, 0.26, -1.6008, 0.3489, -1.9818, 0.0, -1.20, 0.0, -1.57, -1.6008, -0.2489, -1.9818, -0.0, -1.20, 0.0,
                    0.1, 0.36, -1.83, 0.47, -2.27, 0.0, -1.20, 0.0, -1.57, -2.3, 0.0, -2.1, -0.0, -1.20, 0.0]
        meta:
          name: Home
          usage: demo
          description: Go home
      
     