${ARM_SIDE_PREFIX}_cartesian_vel_controller:
  ros__parameters:
    type: tsid_controllers/CartesianVelocityController
    
    joint_state_names:
      - ${ARM_SIDE_PREFIX}_1_joint
      - ${ARM_SIDE_PREFIX}_2_joint
      - ${ARM_SIDE_PREFIX}_3_joint
      - ${ARM_SIDE_PREFIX}_4_joint
      - ${ARM_SIDE_PREFIX}_5_joint
      - ${ARM_SIDE_PREFIX}_6_joint
      - ${ARM_SIDE_PREFIX}_7_joint

    joint_command_names:
      - ${ARM_SIDE_PREFIX}_1_joint
      - ${ARM_SIDE_PREFIX}_2_joint
      - ${ARM_SIDE_PREFIX}_3_joint
      - ${ARM_SIDE_PREFIX}_4_joint
      - ${ARM_SIDE_PREFIX}_5_joint
      - ${ARM_SIDE_PREFIX}_6_joint
      - ${ARM_SIDE_PREFIX}_7_joint

    interface_name: position

    ee_names:
      - ${ARM_SIDE_PREFIX}_7_link

    velocity_scaling: 1.0

    posture_gain: 1.0




